CREATE TABLE IF NOT EXISTS HocSinh (
    MaHS INTEGER PRIMARY KEY AUTOINCREMENT,
    TenHS TEXT NOT NULL,
    Lop TEXT NOT NULL,
    NgaySinh TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SucKhoe (
    MaSK INTEGER PRIMARY KEY AUTOINCREMENT,
    MaHS INTEGER NOT NULL,
    ChieuCao REAL NOT NULL,
    CanNang REAL NOT NULL,
    NgayKham TEXT NOT NULL,
    FOREIGN KEY (MaHS) REFERENCES HocSinh(MaHS)
);
